[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/C/rpc"
flare = "https://flare-api.flare.network/ext/C/rpc"

[etherscan]
coston2 = { key = "${ETHERSCAN_API_KEY}", url = "https://coston2-explorer.flare.network/api" }
flare = { key = "${ETHERSCAN_API_KEY}", url = "https://flare-explorer.flare.network/api" }
